var welcome_text = "<p>Welcome to the experiment. This experiment should take no longer than 10 minutes.</p> <p>Press any key to begin.</p>";

var instruction_text = "<p>Please read these instructions carefully.</p>"+"<p>This study is being conducted by Jackie Spear in the Department of Psychology. You will be asked to study a list of words, and then tested on your memory performance on these same words. At test, some of the words will be previously studied words, and some will be new. Your job will be to indicate that either yes, you did previously study a word, or no, you did not. The study is computer mediated and it takes approximately 15 minutes to complete. Also, when prompted to provide a word, respond by typing in the word 'puppy'. You will receive one credit in exchange for your participation. The researcher may be contacted by email at umspear@myumanitoba.ca.</p>"+"<p>Press any key to begin.</p>";

var instruction_text = "<p>Please read these instructions carefully.</p>"+"<p>This study is being conducted by Jackie Spear in the Department of Psychology. You will be asked to study a list of 40 words, after which you will be given a memory test for these words. When each word is presented, you will be presented with 1 of 2 instructions. Some of the time, you will see the instruction <span style=color:green>TYPE</span>, where your job will be to <b>type the word you just saw</b>. Other times, you will see the instruction <span style=color:red>READ</span>, were your job will be to do nothing, and <b>simply read that word silently.</b> Note that the words you type will not show up on the screen, but will be recorded.</p><p>At test, some of the words will be previously studied words, and some will be new. Your job will be to indicate that either yes, you did previously study a word, or no, you did not. The study is computer mediated and takes approximately 10 minutes to complete. Also, when prompted to provide the answer, respond by typing in the answer to 2+2 = __. You will receive one credit in exchange for your participation. The researcher may be contacted by email at umspear@myumanitoba.ca.</p><p>Press any key to begin.</p>";

var post_practice_text = "<p>Remember! When you see the instruction <span style=color:green;font-weight:bold>TYPE</span> you must <b>TYPE the word that is presented.</b> When you see the instruction <span style=color:red;font-weight:bold>READ</span>, your job will be to do nothing, and <b>simply READ that word silently.</b></p>"+"<p>Typing is being recorded. Press 'w' to continue.</p>";


var attention_check_text = "Provide the answer:";

var fullscreen_prompt = "<p><b>Please turn off all background audio for the experiment</b>. Do not continue until you have turned off all other audio.</p>"+"<p>Also, remain in fullscreen mode for the entire experiment. The experiment will switch to full screen mode when you press the button below. It will also record if you exit fullscreen mode.</p>";

var debrief_text = "<p>In a recognition experiment, participants discriminate words that were studied in a training list from words that were not presented in the training list. As you may have noticed, in this study the amount of word relatedness was altered. Specifcally, words that had usual pronunciations and unusual pronunciations were selected. We hope to obtain a distinctiveness effect, where unusual words have a memorial benefit when presented among a list of usual words. In addition, some of these words you were instructed to type, and others to simply read. We hope to obtain a well known Production Effect, where produced words are better remembered than unproduced words. In conjunction with this, we are going to use a computational model of natural language processing, called Latent Semantic Analysis, to derive predictions that are consistent with human performance. The ultimate goal of this research is to be able to derive predictions about distinctiveness a priori using computational models. This study contained no deception or experimental manipulation of any kind. You can learn more about this line of work from our laboratory webpage located at: home.cc.umanitoba.ca/~jamiesor</p><p>Press any key to finish the experiment.</p><br><p>Thank you for your help,<br>Jackie Spear<br>Ph.D. Student<br>Department of Psychology<br>University of Manitoba</p>";


var test_instruction_text = "<p>Take a rest if you need.</p>"+"<p>Next, your job will be to indicate whether you previously studied a word by pressing 'y', otherwise press 'n'. Keep your index fingers on these keys.</p>"+"<p>When you are ready press 'i' to continue.</p>";
