studywords_read2 = [
{"stimulus":"<p style='font-size: 48px;'>RADISH - <span style='color: red'>PEAR</span></p>","data":{"type":"old","category":"read","word":"RADISH - PEAR"}},
{"stimulus":"<p style='font-size: 48px;'>CHAPLAIN - <span style='color: red'>MINISTER</span></p>","data":{"type":"old","category":"read","word":"CHAPLAIN - MINISTER"}},
{"stimulus":"<p style='font-size: 48px;'>ENTREE - <span style='color: red'>DISH</span></p>","data":{"type":"old","category":"read","word":"ENTREE - DISH"}},
{"stimulus":"<p style='font-size: 48px;'>PAMPHLET - <span style='color: red'>LEAFLET</span></p>","data":{"type":"old","category":"read","word":"PAMPHLET - LEAFLET"}},
/*{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>FLAUNT</p>","data":{"type":"old","category":"abstract","word":"FLAUNT"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>THRIFT</p>","data":{"type":"old","category":"abstract","word":"THRIFT"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>CHEAT</p>","data":{"type":"old","category":"abstract","word":"CHEAT"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>GUESSWORK</p>","data":{"type":"old","category":"abstract","word":"GUESSWORK"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>CHASTITY</p>","data":{"type":"old","category":"abstract","word":"CHASTITY"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>CORDIAL</p>","data":{"type":"old","category":"abstract","word":"CORDIAL"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>DREAMLAND</p>","data":{"type":"old","category":"abstract","word":"DREAMLAND"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>LINGO</p>","data":{"type":"old","category":"abstract","word":"LINGO"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>GODSEND</p>","data":{"type":"old","category":"abstract","word":"GODSEND"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>GRADUAL</p>","data":{"type":"old","category":"abstract","word":"GRADUAL"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>DAZE</p>","data":{"type":"old","category":"abstract","word":"DAZE"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>TRIFLE</p>","data":{"type":"old","category":"abstract","word":"TRIFLE"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>ROWDY</p>","data":{"type":"old","category":"abstract","word":"ROWDY"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>PEACETIME</p>","data":{"type":"old","category":"abstract","word":"PEACETIME"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>STARTLE</p>","data":{"type":"old","category":"abstract","word":"STARTLE"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>EXHAUST</p>","data":{"type":"old","category":"abstract","word":"EXHAUST"}}, 
{"stimulus":"<p style='font-size: 48px;'>] */
]