studywords_concrete = [
{"stimulus":"<p style='font-size: 48px;'>RADISH - <span style='color: green'>PEAR</span></p>","data":{"type":"old","category":"produce","word":"RADISH - PEAR"}},
{"stimulus":"<p style='font-size: 48px;'>CHAPLAIN - <span style='color: green'>MINISTER</span></p>","data":{"type":"old","category":"produce","word":"CHAPLAIN - MINISTER"}},
{"stimulus":"<p style='font-size: 48px;'>ENTREE - <span style='color: green'>DISH</span></p>","data":{"type":"old","category":"produce","word":"ENTREE - DISH"}},
{"stimulus":"<p style='font-size: 48px;'>PAMPHLET - <span style='color: green'>LEAFLET</span></p>","data":{"type":"old","category":"produce","word":"PAMPHLET - LEAFLET"}},
/*{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>FLEECE</p>","data":{"type":"old","category":"concrete","word":"FLEECE"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>LOCUST</p>","data":{"type":"old","category":"concrete","word":"LOCUST"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>APPLIANCE</p>","data":{"type":"old","category":"concrete","word":"APPLIANCE"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>SIRLOIN</p>","data":{"type":"old","category":"concrete","word":"SIRLOIN"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>SENTRY</p>","data":{"type":"old","category":"concrete","word":"SENTRY"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>PLAID</p>","data":{"type":"old","category":"concrete","word":"PLAID"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>GASH</p>","data":{"type":"old","category":"concrete","word":"GASH"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>NARCOTIC</p>","data":{"type":"old","category":"concrete","word":"NARCOTIC"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>DIAGRAM</p>","data":{"type":"old","category":"concrete","word":"DIAGRAM"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>LACQUER</p>","data":{"type":"old","category":"concrete","word":"LACQUER"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>PLATEAU</p>","data":{"type":"old","category":"concrete","word":"PLATEAU"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>ADHESIVE</p>","data":{"type":"old","category":"concrete","word":"ADHESIVE"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>MILITIA</p>","data":{"type":"old","category":"concrete","word":"MILITIA"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>FIREBALL</p>","data":{"type":"old","category":"concrete","word":"FIREBALL"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>EMPEROR</p>","data":{"type":"old","category":"concrete","word":"EMPEROR"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>MASCOT</p>","data":{"type":"old","category":"concrete","word":"MASCOT"}}, */
]