testwords = [
{"stimulus":"<p style='font-size: 48px;'>DRAW</p>","data":{"type":"old","category":"read","word":"DRAW"}},
{"stimulus":"<p style='font-size: 48px;'>CONFIDENCE</p>","data":{"type":"old","category":"read","word":"CONFIDENCE"}},
{"stimulus":"<p style='font-size: 48px;'>HONEST</p>","data":{"type":"old","category":"read","word":"HONEST"}},
{"stimulus":"<p style='font-size: 48px;'>TUNE</p>","data":{"type":"old","category":"read","word":"TUNE"}},
{"stimulus":"<p style='font-size: 48px;'>PEAR</p>","data":{"type":"old","category":"produce","word":"PEAR"}},
{"stimulus":"<p style='font-size: 48px;'>MINISTER</p>","data":{"type":"old","category":"produce","word":"MINISTER"}},
{"stimulus":"<p style='font-size: 48px;'>DISH</p>","data":{"type":"old","category":"produce","word":"DISH"}},
{"stimulus":"<p style='font-size: 48px;'>LEAFLET</p>","data":{"type":"old","category":"produce","word":"LEAFLET"}},

/*{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>FLAUNT</p>","data":{"type":"old","category":"abstract","word":"FLAUNT"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>THRIFT</p>","data":{"type":"old","category":"abstract","word":"THRIFT"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>CHEAT</p>","data":{"type":"old","category":"abstract","word":"CHEAT"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>GUESSWORK</p>","data":{"type":"old","category":"abstract","word":"GUESSWORK"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>CHASTITY</p>","data":{"type":"old","category":"abstract","word":"CHASTITY"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>CORDIAL</p>","data":{"type":"old","category":"abstract","word":"CORDIAL"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>DREAMLAND</p>","data":{"type":"old","category":"abstract","word":"DREAMLAND"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>LINGO</p>","data":{"type":"old","category":"abstract","word":"LINGO"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>GODSEND</p>","data":{"type":"old","category":"abstract","word":"GODSEND"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>GRADUAL</p>","data":{"type":"old","category":"abstract","word":"GRADUAL"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>DAZE</p>","data":{"type":"old","category":"abstract","word":"DAZE"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>TRIFLE</p>","data":{"type":"old","category":"abstract","word":"TRIFLE"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>ROWDY</p>","data":{"type":"old","category":"abstract","word":"ROWDY"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>PEACETIME</p>","data":{"type":"old","category":"abstract","word":"PEACETIME"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>STARTLE</p>","data":{"type":"old","category":"abstract","word":"STARTLE"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>EXHAUST</p>","data":{"type":"old","category":"abstract","word":"EXHAUST"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>REBOUND</p>","data":{"type":"new","category":"abstract","word":"REBOUND"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>JIFFY</p>","data":{"type":"new","category":"abstract","word":"JIFFY"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>DEBACLE</p>","data":{"type":"new","category":"abstract","word":"DEBACLE"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>LEEWAY</p>","data":{"type":"new","category":"abstract","word":"LEEWAY"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>DAYDREAM</p>","data":{"type":"new","category":"abstract","word":"DAYDREAM"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>POISE</p>","data":{"type":"new","category":"abstract","word":"POISE"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>RUSH</p>","data":{"type":"new","category":"abstract","word":"RUSH"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>DECREASE</p>","data":{"type":"new","category":"abstract","word":"DECREASE"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>ANCESTRY</p>","data":{"type":"new","category":"abstract","word":"ANCESTRY"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>MISHAP</p>","data":{"type":"new","category":"abstract","word":"MISHAP"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>STILLNESS</p>","data":{"type":"new","category":"abstract","word":"STILLNESS"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>AMATEUR</p>","data":{"type":"new","category":"abstract","word":"AMATEUR"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>GIMMICK</p>","data":{"type":"new","category":"abstract","word":"GIMMICK"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>DRAWBACK</p>","data":{"type":"new","category":"abstract","word":"DRAWBACK"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>OVERHAUL</p>","data":{"type":"new","category":"abstract","word":"OVERHAUL"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>COMEBACK</p>","data":{"type":"new","category":"abstract","word":"COMEBACK"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>PLEDGE</p>","data":{"type":"new","category":"abstract","word":"PLEDGE"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>RIDDLE</p>","data":{"type":"new","category":"abstract","word":"RIDDLE"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>SNUG</p>","data":{"type":"new","category":"abstract","word":"SNUG"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>BEGINNER</p>","data":{"type":"new","category":"abstract","word":"BEGINNER"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>RADISH</p>","data":{"type":"old","category":"concrete","word":"RADISH"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>CHAPLAIN</p>","data":{"type":"old","category":"concrete","word":"CHAPLAIN"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>ENTREE</p>","data":{"type":"old","category":"concrete","word":"ENTREE"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>PAMPHLET</p>","data":{"type":"old","category":"concrete","word":"PAMPHLET"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>FLEECE</p>","data":{"type":"old","category":"concrete","word":"FLEECE"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>LOCUST</p>","data":{"type":"old","category":"concrete","word":"LOCUST"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>APPLIANCE</p>","data":{"type":"old","category":"concrete","word":"APPLIANCE"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>SIRLOIN</p>","data":{"type":"old","category":"concrete","word":"SIRLOIN"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>SENTRY</p>","data":{"type":"old","category":"concrete","word":"SENTRY"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>PLAID</p>","data":{"type":"old","category":"concrete","word":"PLAID"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>GASH</p>","data":{"type":"old","category":"concrete","word":"GASH"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>NARCOTIC</p>","data":{"type":"old","category":"concrete","word":"NARCOTIC"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>DIAGRAM</p>","data":{"type":"old","category":"concrete","word":"DIAGRAM"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>LACQUER</p>","data":{"type":"old","category":"concrete","word":"LACQUER"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>PLATEAU</p>","data":{"type":"old","category":"concrete","word":"PLATEAU"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>ADHESIVE</p>","data":{"type":"old","category":"concrete","word":"ADHESIVE"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>MILITIA</p>","data":{"type":"old","category":"concrete","word":"MILITIA"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>FIREBALL</p>","data":{"type":"old","category":"concrete","word":"FIREBALL"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>EMPEROR</p>","data":{"type":"old","category":"concrete","word":"EMPEROR"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>MASCOT</p>","data":{"type":"old","category":"concrete","word":"MASCOT"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>CLEFT</p>","data":{"type":"new","category":"concrete","word":"CLEFT"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>HOIST</p>","data":{"type":"new","category":"concrete","word":"HOIST"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>SNEEZE</p>","data":{"type":"new","category":"concrete","word":"SNEEZE"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>BOUTIQUE</p>","data":{"type":"new","category":"concrete","word":"BOUTIQUE"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>STIMULANT</p>","data":{"type":"new","category":"concrete","word":"STIMULANT"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>MONARCH</p>","data":{"type":"new","category":"concrete","word":"MONARCH"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>TALISMAN</p>","data":{"type":"new","category":"concrete","word":"TALISMAN"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>CADAVER</p>","data":{"type":"new","category":"concrete","word":"CADAVER"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>NOVELIST</p>","data":{"type":"new","category":"concrete","word":"NOVELIST"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>HAIRCUT</p>","data":{"type":"new","category":"concrete","word":"HAIRCUT"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>JUROR</p>","data":{"type":"new","category":"concrete","word":"JUROR"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>SLIP</p>","data":{"type":"new","category":"concrete","word":"SLIP"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>PLUM</p>","data":{"type":"new","category":"concrete","word":"PLUM"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>SKEWER</p>","data":{"type":"new","category":"concrete","word":"SKEWER"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>SALVE</p>","data":{"type":"new","category":"concrete","word":"SALVE"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>CONTINENT</p>","data":{"type":"new","category":"concrete","word":"CONTINENT"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>BICYCLE</p>","data":{"type":"new","category":"concrete","word":"BICYCLE"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>QUARRY</p>","data":{"type":"new","category":"concrete","word":"QUARRY"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>MOONSHINE</p>","data":{"type":"new","category":"concrete","word":"MOONSHINE"}},
{"stimulus":"<p style='font-size: 48px;'>{"stimulus":"<p style='font-size: 48px;'>ASPHALT</p>","data":{"type":"new","category":"concrete","word":"ASPHALT"}},
*/
]